CREATE DATABASE IF NOT EXISTS wordpress;
USE wordpress;

CREATE USER '$(MYSQL_USER)'@'%' IDENTIFIED BY '$(MYSQL_PASSWORD)';
GRANT ALL PRIVILEGES ON wordpress.* TO '$(MYSQL_USER)'@'%';

CREATE USER '$(WP_USER)'@'%' IDENTIFIED BY '$(WP_PASSWORD)';
GRANT SELECT, INSERT, UPDATE, DELETE ON wordpress.* TO '$(WP_USER)'@'%';

FLUSH PRIVILEGES;