version: "3.8"

services:
  nginx:
    build: ./src/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./src/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: ./src/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: redis
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network

  mariadb:
    build: ./src/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/mariadb/conf.d:/etc/mysql/conf.d:ro
    networks:
      - inception_network


  redis:
    build: ./src/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception_network


  ftp:
    build: ./src/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  adminer:
    build: ./src/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception_network

  teaser:
    build: ./src/bonus/website
    container_name: teaser
    restart: always
    ports:
      - "8081:80"
    networks:
      - inception_network

  uptime-kuma:
    build: ./src/bonus/uptime-kuma
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - inception_network

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hulefevr/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/hulefevr/data/mariadb'	
  uptime-kuma-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hulefevr/data/uptime-kuma'

networks:
  inception_network:
