version: "3.8"

services:
  nginx:
    build: ./src/nginx
    container_name: nginx
    restart: always
    ports:
      - "8443:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./src/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: ./src/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: redis
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network

  mariadb:
    build: ./src/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/mariadb/conf.d:/etc/mysql/conf.d:ro
    networks:
      - inception_network


  redis:
    build: ./src/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception_network



volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception_network:
